# Generated by Django 4.1 on 2022-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='date_time',
        ),
    ]
