# Generated by Django 4.1 on 2022-09-10 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0002_remove_measurements_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 24, 29, 101597)),
        ),
    ]
