# Generated by Django 4.1 on 2022-09-10 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0003_measurements_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
